# GLOBAL SETTINGS
cname: swellnet-2018.yourwebvisual.com
allow_robots: false

# META
title: Swellnet
title_homepage: Swellnet
company: Swellnet Pty Ltd
description:

# DEVELOPER
github_repo_owner: liquidvisual
github_repo_path: https://github.com/liquidvisual/swell-0918
github_repo_name: swell-0918
jekyll_version: 3.7.0

# OFFICES
offices:
  - title: Sydney
    address: Level 5, 8 West Street<br> North Sydney, NSW, 2060
    phone: 1800 793 556
    email: privacy@swellnet.com

# GOOGLE
google_analytics: #UA-XXXXXXXX-X

# AUTHOR
author:
  title:
  url:
  logo:
  description: